### ISSUE TITLE
Feature: Logfiles

### ISSUE THREAD

**Issue by eykrehbein** [eykrehbein/strest#79]
Add an option to the cli command to create a log file. Formatted as Json array with an entry for each request where response code, data, headers and a possible error is logged?

**Comment by jgroom33** [comment]
Seems reasonable.
There's this to help: https://github.com/winstonjs/winston/blob/master/README.md
Are you thinking we just cut everything to logging and abandon the cli output?

**Comment by eykrehbein** [comment]
@jgroom33 I think the cli output should stay as it is because this quick response is a key factor in my opinion. We can just make the file output optional.

**Comment by jgroom33** [comment]
I'm assuming logging could output to stdout and optionally a file. this might simplify the code. but, the fancy colorized output would no longer exist

**Comment by eykrehbein** [comment]
What is more attractive for professional usage? The more descriptive logging style as it is rn or just blank stdout logs?

**Comment by jgroom33** [comment]
typically, I think json is useful when there is a need for another system to analyze the data.
the primary use I'm concerned with is for CI. for that purpose, the most important things are:
Is there an ability to return exit code of 0 or non 0?
when the exit code is not 0, what data can be displayed to a human to assist with identifying the issue?
so, for this use, json structure does not provide additional value (since a human is using the data). therefore, whatever is easiest to develop is best.
at the same time, a json report might be beneficial to show metadata (number of tests, execution time)

the existing cli output is very nice. I think it helps for casual use (non CI) and provides the average postman user with a friendly output.

if we assume both outputs (cli and json) are useful, then we should ask: are they both useful simultaneously? 
an implementation option is `--format=(colorized, json)`

perhaps we look at the newman usage of `--report` and somewhat mimic that.
