### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#92]
Create a UI

`strest-ui /tests` loads all requests into visualization (use similar layout to insomnia UI)
Allow stepping through requests and displaying results
Requests can be modified and saved back to disk
Values of variables are displayed along side the 'code': i.e. 
Env(FOO)`bar`

**Comment by eykrehbein** [comment]
Also had this idea... I'm currently working on version 2.0.0 which will split strest into two separate parts: 

- the _strest-api_, which is basically a node library with all the functions behind strest and with no interface or output
- the _strest-cli_, which is just a cli interface which will call the _strest-api_ functions

When 2.0 is out, it will be a lot easier to create a UI App, because the App will just call functions from the _strest-api_ like the cli does.

**Comment by jgroom33** [comment]
Another implementation option is to write a plug-in for vscode. This might be better aligned with the focus on committing the tests to version control.
What do you think of that option?

**Comment by jgroom33** [comment]
https://github.com/Huachao/vscode-restclient/blob/master/README.md

**Comment by eykrehbein** [comment]
Also a nice approach

**Comment by jgroom33** [comment]
https://github.com/Huachao/vscode-restclient/issues/287

Perhaps we should change the syntax of all the variable inputs from Val(foo) to {{$Val foo}}
Handlebars are a more common convention.

**Comment by jgroom33** [comment]
I think standardizing the request format is useful.

http://www.softwareishard.com/blog/har-12-spec/#request

This way it would be easy to fork and update the vscode project.
Then the vscode project could use the API you're developing.

**Comment by jgroom33** [comment]
added a video to show the flow:
https://github.com/jgroom33/vscode-strest-client

**Comment by eykrehbein** [comment]
awesome!
